// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DryRunRule(arg1, arg2) {
  return window['go']['main']['App']['DryRunRule'](arg1, arg2);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function GetAllRules() {
  return window['go']['main']['App']['GetAllRules']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetRawDataList(arg1, arg2) {
  return window['go']['main']['App']['GetRawDataList'](arg1, arg2);
}

export function GetRuleByTag(arg1) {
  return window['go']['main']['App']['GetRuleByTag'](arg1);
}

export function GetTaggedDataList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTaggedDataList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTaskBatches() {
  return window['go']['main']['App']['GetTaskBatches']();
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function RollbackTask(arg1) {
  return window['go']['main']['App']['RollbackTask'](arg1);
}

export function RunTaggingTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunTaggingTask'](arg1, arg2, arg3);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}
