// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {taglogic} from '../models';
import {config} from '../models';
import {main} from '../models';

export function AnalyzeDataFile():Promise<model.FileAnalysisResult>;

export function ChatWithAI(arg1:string):Promise<string>;

export function CheckTagHasRules(arg1:number):Promise<boolean>;

export function CreateDataset(arg1:string,arg2:string):Promise<model.SysDataset>;

export function CreateTag(arg1:model.SysTag):Promise<void>;

export function DeleteDataset(arg1:number):Promise<void>;

export function DeleteRawData(arg1:Array<number>):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function DeleteTaskBatches(arg1:Array<number>):Promise<void>;

export function DryRunRule(arg1:string,arg2:number):Promise<Array<taglogic.DryRunResult>>;

export function ExportData(arg1:number,arg2:string):Promise<void>;

export function ExportTaggedDataList(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function ExportTags(arg1:string):Promise<void>;

export function ExportTaskLogsCSV(arg1:number):Promise<string>;

export function GetAllRules():Promise<Array<model.SysMatchRule>>;

export function GetAllTags():Promise<Array<model.SysTag>>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetAvailableDataSources():Promise<Array<model.DataSourceOption>>;

export function GetDashboardStats():Promise<model.DashboardStats>;

export function GetRawDataList(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.PagedData>;

export function GetRuleByTag(arg1:number):Promise<model.SysMatchRule>;

export function GetTagTree():Promise<Array<model.TagTreeNode>>;

export function GetTaggedDataList(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:number):Promise<model.PagedTaggedData>;

export function GetTaskBatches():Promise<Array<model.TagTaskBatch>>;

export function GetTaskLogs(arg1:number):Promise<Array<model.TagTaskLogDto>>;

export function ImportData(arg1:string,arg2:Array<string>,arg3:number,arg4:string):Promise<number>;

export function ImportTags(arg1:string):Promise<void>;

export function ListDatasets():Promise<Array<model.SysDataset>>;

export function RollbackTask(arg1:number):Promise<void>;

export function RunTaggingTask(arg1:Array<number>,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<number>;

export function SaveAppConfig(arg1:config.AppConfig):Promise<void>;

export function SaveRule(arg1:model.SysMatchRule):Promise<void>;

export function UpdateDataset(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateTag(arg1:model.SysTag):Promise<void>;
