// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {taglogic} from '../models';
import {config} from '../models';
import {main} from '../models';

export function ChatWithAI(arg1:string):Promise<string>;

export function CreateTag(arg1:model.SysTag):Promise<void>;

export function DeleteRawData(arg1:Array<number>):Promise<void>;

export function DryRunRule(arg1:string,arg2:number):Promise<Array<taglogic.DryRunResult>>;

export function ExportData(arg1:number,arg2:string):Promise<void>;

export function GetAllRules():Promise<Array<model.SysMatchRule>>;

export function GetAllTags():Promise<Array<model.SysTag>>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetDashboardStats():Promise<model.DashboardStats>;

export function GetRawDataList(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.PagedData>;

export function GetRuleByTag(arg1:number):Promise<model.SysMatchRule>;

export function GetTaggedDataList(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<model.PagedTaggedData>;

export function GetTaskBatches():Promise<Array<model.TagTaskBatch>>;

export function ImportData(arg1:string):Promise<number>;

export function RollbackTask(arg1:number):Promise<void>;

export function RunTaggingTask(arg1:Array<number>,arg2:string,arg3:boolean):Promise<number>;

export function SaveAppConfig(arg1:config.AppConfig):Promise<void>;

export function SaveRule(arg1:model.SysMatchRule):Promise<void>;
