// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDataFile() {
  return window['go']['main']['App']['AnalyzeDataFile']();
}

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function CheckTagHasRules(arg1) {
  return window['go']['main']['App']['CheckTagHasRules'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteRawData(arg1) {
  return window['go']['main']['App']['DeleteRawData'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTaskBatches(arg1) {
  return window['go']['main']['App']['DeleteTaskBatches'](arg1);
}

export function DryRunRule(arg1, arg2) {
  return window['go']['main']['App']['DryRunRule'](arg1, arg2);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function ExportTags(arg1) {
  return window['go']['main']['App']['ExportTags'](arg1);
}

export function ExportTaskLogsCSV(arg1) {
  return window['go']['main']['App']['ExportTaskLogsCSV'](arg1);
}

export function GetAllRules() {
  return window['go']['main']['App']['GetAllRules']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetRawDataList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRawDataList'](arg1, arg2, arg3, arg4);
}

export function GetRuleByTag(arg1) {
  return window['go']['main']['App']['GetRuleByTag'](arg1);
}

export function GetTagTree() {
  return window['go']['main']['App']['GetTagTree']();
}

export function GetTaggedDataList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTaggedDataList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetTaskBatches() {
  return window['go']['main']['App']['GetTaskBatches']();
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function ImportData(arg1, arg2) {
  return window['go']['main']['App']['ImportData'](arg1, arg2);
}

export function ImportTags(arg1) {
  return window['go']['main']['App']['ImportTags'](arg1);
}

export function RollbackTask(arg1) {
  return window['go']['main']['App']['RollbackTask'](arg1);
}

export function RunTaggingTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunTaggingTask'](arg1, arg2, arg3, arg4);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}
