// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDataFile() {
  return window['go']['main']['App']['AnalyzeDataFile']();
}

export function ChatWithAI(arg1) {
  return window['go']['main']['App']['ChatWithAI'](arg1);
}

export function CheckTagHasRules(arg1) {
  return window['go']['main']['App']['CheckTagHasRules'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateDataset(arg1, arg2) {
  return window['go']['main']['App']['CreateDataset'](arg1, arg2);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteDataset(arg1) {
  return window['go']['main']['App']['DeleteDataset'](arg1);
}

export function DeleteRawData(arg1) {
  return window['go']['main']['App']['DeleteRawData'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DeleteSqlTemplate(arg1) {
  return window['go']['main']['App']['DeleteSqlTemplate'](arg1);
}

export function DeleteSystemTableRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteSystemTableRecord'](arg1, arg2);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTaskBatches(arg1) {
  return window['go']['main']['App']['DeleteTaskBatches'](arg1);
}

export function DeleteVirtualRecord(arg1) {
  return window['go']['main']['App']['DeleteVirtualRecord'](arg1);
}

export function DryRunRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['DryRunRule'](arg1, arg2, arg3);
}

export function ExecuteRawSQL(arg1) {
  return window['go']['main']['App']['ExecuteRawSQL'](arg1);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function ExportDatasetWithRules(arg1, arg2) {
  return window['go']['main']['App']['ExportDatasetWithRules'](arg1, arg2);
}

export function ExportTaggedDataList(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['ExportTaggedDataList'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ExportTags(arg1) {
  return window['go']['main']['App']['ExportTags'](arg1);
}

export function ExportTaskLogsCSV(arg1) {
  return window['go']['main']['App']['ExportTaskLogsCSV'](arg1);
}

export function GetAllRules() {
  return window['go']['main']['App']['GetAllRules']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppPaths() {
  return window['go']['main']['App']['GetAppPaths']();
}

export function GetAvailableSourceFiles(arg1) {
  return window['go']['main']['App']['GetAvailableSourceFiles'](arg1);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetRawDataList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetRawDataList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRulesByDataset(arg1) {
  return window['go']['main']['App']['GetRulesByDataset'](arg1);
}

export function GetRulesByTag(arg1) {
  return window['go']['main']['App']['GetRulesByTag'](arg1);
}

export function GetSqlTemplates() {
  return window['go']['main']['App']['GetSqlTemplates']();
}

export function GetSystemTables() {
  return window['go']['main']['App']['GetSystemTables']();
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTagTree() {
  return window['go']['main']['App']['GetTagTree']();
}

export function GetTaggedDataList(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['GetTaggedDataList'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function GetTaskBatches() {
  return window['go']['main']['App']['GetTaskBatches']();
}

export function GetTaskLogs(arg1) {
  return window['go']['main']['App']['GetTaskLogs'](arg1);
}

export function GetVirtualDatasetData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetVirtualDatasetData'](arg1, arg2, arg3);
}

export function ImportData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportData'](arg1, arg2, arg3, arg4);
}

export function ImportDatasetWithRules(arg1) {
  return window['go']['main']['App']['ImportDatasetWithRules'](arg1);
}

export function ImportExternalDatabase() {
  return window['go']['main']['App']['ImportExternalDatabase']();
}

export function ImportTags(arg1) {
  return window['go']['main']['App']['ImportTags'](arg1);
}

export function InsertSystemTableRecord(arg1, arg2) {
  return window['go']['main']['App']['InsertSystemTableRecord'](arg1, arg2);
}

export function InsertVirtualRecord(arg1, arg2) {
  return window['go']['main']['App']['InsertVirtualRecord'](arg1, arg2);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListDatasets() {
  return window['go']['main']['App']['ListDatasets']();
}

export function MoveTag(arg1, arg2) {
  return window['go']['main']['App']['MoveTag'](arg1, arg2);
}

export function OpenDirectoryInOS(arg1) {
  return window['go']['main']['App']['OpenDirectoryInOS'](arg1);
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function RollbackTask(arg1) {
  return window['go']['main']['App']['RollbackTask'](arg1);
}

export function RunTaggingTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunTaggingTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['main']['App']['SaveCSVFile'](arg1, arg2);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function SaveSqlTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSqlTemplate'](arg1, arg2, arg3);
}

export function TestAIConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestAIConnection'](arg1, arg2, arg3);
}

export function UpdateDataset(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDataset'](arg1, arg2, arg3);
}

export function UpdateSystemTableRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSystemTableRecord'](arg1, arg2, arg3);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}

export function UpdateVirtualRecord(arg1, arg2) {
  return window['go']['main']['App']['UpdateVirtualRecord'](arg1, arg2);
}
